---
- hosts: all
  become: true
  # become_flags: -E # Only used this if the sudo user is not able to download packages
  
  vars:
    # Check the geerlingguy.jenkins role default/main.yml file for more variables that can be modified
    jenkins_package_state: latest # Change this to `latest` to update Jenkins if a newer version is available, this won't remove the previous version
    # jenkins_hostname: "<hostname>"
    jenkins_home: /var/lib/jenkins
    jenkins_jar_location: /opt/jenkins-cli.jar
    # jenkins_proxy_host: "<proxy node or ip>"
    # jenkins_proxy_port: "<port>" #127.0.0.1 and localhost should be the minimum in the no_proxy section
    # jenkins_proxy_noproxy:
      # - 127.0.0.1
      # - localhost
    jenkins_plugins_state: present # Change this to 'latest' to update plugins if newer versions are available.
    jenkins_plugins:
      - pipeline-stage-view
      - ansible
      - uno-choice
      - blueocean
      - dark-theme
      - thinBackup
      - ssh-agent
      - ssh-slaves
      - ssh-steps
      - rebuild
      - ansicolor
    # jenkins_version: "2.375" ## Just uncoment if you really want to specify the version
    # java_packages: ## Same comment as above
      # - java-11-openjdk 
  roles:
    - role: geerlingguy.java
    - role: geerlingguy.jenkins
